Особая конструкция языка, необходимая при осуществлении операции, которая может привести к аварийному завершению программы. Использование менеджера состояний гарантирует, что действия, описанные внутри него будут выполнены **в любом случае**, даже, если не будет вызван деструктор объекта. Для работы с менеджером состояний, для класса объекта должны быть определены [[Dunder-методы|dunder-методы]] ```__enter__ и __exit__```.

Пример без менеджера состояния:
```Python
class Resource:  
    def __enter__(self):  
        print("Подключаюсь к ресурсу")  
        self.conn = "OK"  
        return self.conn  
    def __exit__(self, exc_type, exc_value, traceback):  
        print("Отключаюсь от ресурса")  
        self.conn = None  
  
conn = Resource()  
print("Работаю с:", conn)  
raise Exception("exception")
```
```
Работаю с: <__main__.Resource object at 0x1025ddfd0>
Traceback (most recent call last):
  File "/Users/v.leontiy/Documents/Python/tests.py", line 12, in <module>
    raise Exception("exception")
Exception: exception
```

В данной ситуации, при возникновении исключения ресурс подключения не был освобожден, так как метод ```__exit__``` не был вызван. Чтобы это исправить, воспользуемся менеджером состояния:
```Python
class Resource:  
    def __enter__(self):  
        print("Подключаюсь к ресурсу")  
        self.conn = "OK"  
        return self.conn  
    def __exit__(self, exc_type, exc_value, traceback):  
        print("Отключаюсь от ресурса")  
        self.conn = None  
  
with Resource() as conn:  
    print("Работаю с:", conn)  
    raise Exception("exception")
```
```
Подключаюсь к ресурсу
Работаю с: OK
Отключаюсь от ресурса
Traceback (most recent call last):
  File "/Users/v.leontiy/Documents/Python/tests.py", line 12, in <module>
    raise Exception("exception")
Exception: exception
```

При возникновении ошибки внутри менеджера состояния был вызван метод ```__exit__``` и ресурс был освобожден.